# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins:
- branch: master
  name: pulp_file
- branch: master
  name: pulp_container
- branch: master
  name: pulp_rpm
black: false
check_commit_message: true
cherry_pick_automation: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: false
plugin_app_label: pulp_2to3_migration
plugin_camel: Pulp-2To3-Migration
plugin_camel_short: 2To3-Migration
plugin_caps: PULP-2TO3-MIGRATION
plugin_caps_short: 2TO3-MIGRATION
plugin_dash: pulp-2to3-migration
plugin_dash_short: 2to3-migration
plugin_name: pulp-2to3-migration
plugin_snake: pulp_2to3_migration
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pydocstyle: false
pypi_username: pulp
redmine_project: null
stable_branch: '0.2'
test_bindings: false
test_performance: false
test_s3: false
travis_addtl_services:
- mongodb
travis_notifications:
  irc:
    channels:
    - chat.freenode.net#pulp-build
    on_failure: always
    on_success: change

